#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 22 10:17:22 2020

@author: tvorua
"""

import allel
import numpy as np


#with open( '/Users/tvorua/Downloads/hg38.hybrid.vcf', mode ='r' ) as vcf:
    #dat = vcf.keys()
    #print(dat)

dat = allel.read_vcf('/Users/tvorua/Downloads/hg38.hybrid.vcf')
refer = dat[ 'variants/REF' ]
alter = dat[ 'variants/ALT' ]
a = 0
for i in refer:
    if len(i) != 1 or len(alter[a]) != 1:
        np.delete(refer, a)
        np.delete(alter, a)
    a = a+1
print(refer.size)
        
