#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jan 22 10:17:22 2020

@author: tvorua
"""

import allel
import numpy as np


dat = allel.read_vcf('/Users/tvorua/Downloads/hg38.hybrid.vcf')


chromX = {'POS' : dat['variants/POS'][4120212:], 'REF' : dat['variants/REF'][4120212:],
          'ALT' : dat['variants/ALT'][4120212:], 'GT' : dat['calldata/GT'][4120212:]}



dup = {}
seen = {}

for x in range(chromX['POS'].size):
    
    pos = chromX['POS'][x]
    
    if pos in seen.keys():
    
        dup[pos] = [chromX['REF'][x], chromX['ALT'][x]]
    
    else:
    
        seen[pos] = 1
        
homo = {} 
hetero10 = {} 
hetero01 = {}
     
for x in range(chromX['POS'].size):
    
    gt = chromX['GT'][x][0]
    
    if gt[0] == gt[1]:
        
        homo[chromX['POS'][x]] = gt
        
    elif gt[0] == 1:
        
        hetero10[chromX['POS'][x]] = gt
        
    else:
        hetero01[chromX['POS'][x]] = gt
        
